version: '3.7'
services: 
    app:
        container_name: devcontainercompose2_app
        build: .
        ports: 
            - 8000:80
        volumes: 
            - ./php/src/tesis:/var/www/html/
        tty: true
        depends_on: 
            - mysql
    mysql:
        container_name: devcontainercompose2_mysql
        image: mysql:5.7
        ports: 
            - 9906:3306
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: MY_DATABASE
          MYSQL_USER: MYSQL_USER
          MYSQL_PASSWORD: MYSQL_PASSWORD
    
    
    